objects_host:
- { state: present, name: Object1, ip: 192.168.10.1, tags: ["ansible"] }
- { state: present, name: Object2, ip: 192.168.10.2, tags: ["ansible"] }
- { state: present, name: Object3, ip: 192.168.10.3, tags: ["ansible"] }
- { state: present, name: Object4, ip: 192.168.10.4, tags: ["ansible"] }
- { state: present, name: Object5, ip: 192.168.10.5, tags: ["ansible"] }
- { state: present, name: Object6, ip: 192.168.10.6, tags: ["ansible"] }
- { state: present, name: Object7, ip: 192.168.10.7, tags: ["ansible"] }
- { state: present, name: Object8, ip: 192.168.10.8, tags: ["ansible"] }
- { state: present, name: Object9, ip: 192.168.10.9, tags: ["ansible"] }
- { state: present, name: Object10, ip: 192.168.10.10, tags: ["ansible"] }
- { state: present, name: Object11, ip: 192.168.10.11, tags: ["ansible"] }
- { state: present, name: Object12, ip: 192.168.10.12, tags: ["ansible"] }
- { state: present, name: Object13, ip: 192.168.10.13, tags: ["ansible"] }
- { state: present, name: Object14, ip: 192.168.10.14, tags: ["ansible"] }
- { state: present, name: Object15, ip: 192.168.10.15, tags: ["ansible"] }
- { state: present, name: Object16, ip: 192.168.10.16, tags: ["ansible"] }
- { state: present, name: Object17, ip: 192.168.10.17, tags: ["ansible"] }
- { state: present, name: Object18, ip: 192.168.10.18, tags: ["ansible"] }
- { state: present, name: Object19, ip: 192.168.10.19, tags: ["ansible"] }
- { state: present, name: Object20, ip: 192.168.10.20, tags: ["ansible"] }
- { state: present, name: Object21, ip: 192.168.10.21, tags: ["ansible"] }
- { state: present, name: Object22, ip: 192.168.10.22, tags: ["ansible"] }
- { state: present, name: Object23, ip: 192.168.10.23, tags: ["ansible"] }
- { state: present, name: Object24, ip: 192.168.10.24, tags: ["ansible"] }
- { state: present, name: Object25, ip: 192.168.10.25, tags: ["ansible"] }
- { state: present, name: Object26, ip: 192.168.10.26, tags: ["ansible"] }
- { state: present, name: Object27, ip: 192.168.10.27, tags: ["ansible"] }
- { state: present, name: Object28, ip: 192.168.10.28, tags: ["ansible"] }
- { state: present, name: Object29, ip: 192.168.10.29, tags: ["ansible"] }
- { state: present, name: Object30, ip: 192.168.10.30, tags: ["ansible"] }